OpenTicketing/openticketing/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls import url

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('', include('web_app.urls')),
    path('tickets/', include('tickets.urls')),
    path('admin/', admin.site.urls),
    url(r'^api/auth/login$', obtain_jwt_token, name='api-login'),
    path('', include('frontend.urls')),
]

urlpatterns += staticfiles_urlpatterns()

OpenTicketing/tickets/urls.py
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenTicketing, 
#    Copyright (C) 2019-2020 OpenTicketing (<https://github.com/loghmanb/OpenTicketing>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

from tickets.app_views.pages.dashboard import dashboard
from tickets.app_views.tickets.my_tickets import MyTickets
from tickets.app_views.tickets.ticket import TicketView


app_name = 'tickets'

urlpatterns = [
    path('', dashboard, name='home'),
    path('ticket/<int:id>', login_required(TicketView.as_view()), name='ticket'),

    path('dashboard/', dashboard, name='dashboard'),
    path('submitter/<int:id>', views.submitter, name='submitter'),

    path('my_tickets/', MyTickets.as_view(), name='customer-my-tickets'),
    path('submit/', views.submit, name='submit'),

    url('api/', include(('tickets.api.urls', 'tickets'), namespace="ticket-api")),
]

OpenTicketing/web_app/urls.py
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenTicketing, 
#    Copyright (C) 2019-2020 OpenTicketing (<https://github.com/loghmanb/OpenTicketing>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('standard', views.home, name='home'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='openticketing/logout.html'), name='logout'),
    path('user-profile/', views.user_profile, name='user-profile'),
    path('user-settings/', views.user_setting, name='user-settings'),
]

OpenTicketing/templates/openticketing/partials/_footer.html
<footer class="sticky-footer footer container">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
             <span>Copyright &copy; OpenTicketing 2019-2020</span>
        </div>
    </div>
</footer>
<!-- End of Footer -->

OpenTicketing/templates/openticketing/partials/_header.html
<div class="navbar">
    <a href="{% url 'tickets:home' %}" class="navbar-brand">Home</a>
    <a href="{% url 'tickets:home' %}" class="navbar-brand">Knowledgebase</a>
    <a href="{% url 'tickets:about' %}" class="navbar-item">About</a>
    <a href="{% url 'tickets:contact' %}" class="navbar-item">Contact</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'tickets:logout' %}" class="navbar-item">Logout</a>
    {% else %}
    <a href="{% url 'tickets:login' %}" class="navbar-item">Login</a>
    {% endif %}
</div>

OpenTicketing/templates/openticketing/partials/_sidebar.html
{% load static %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'web:home' %}">
        <div class="sidebar-brand-icon">
          <img src="{% static 'openticketing/img/logo.png' %}" class="img-fluid" />
        </div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      {% block sidebar_menu %}
      {% endblock sidebar_menu %}
      
      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Knowledgebase
      </div>

      <!-- Nav Item - Knowledgebase -->
      <li class="nav-item">
        <a class="nav-link" href="tables.html">
          <i class="fas fa-fw fa-table"></i>
          <span>Post an article</span></a>
      </li>


      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

OpenTicketing/templates/openticketing/partials/_sidebar_client.html
{% extends 'openticketing/partials/_sidebar.html' %}
{% block sidebar_menu %}
      <!-- Nav Item - Dashboard -->
      <li {% if 'dashboard' in request.path %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
        <a class="nav-link" href="{% url 'tickets:dashboard' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Mailbox
      </div>

      <li class="nav-item" >
        <a class="nav-link" href="% url 'mailbox:inbox' %">
          <i class="fas fa-fw fa-table"></i>
          <span>Inbox</span></a>
      </li>

      <li class="nav-item" >
        <a class="nav-link" href="% url 'mailbox:inbox' %">
          <i class="fas fa-fw fa-table"></i>
          <span>Sent Mail</span></a>
      </li>

      <li class="nav-item" >
        <a class="nav-link" href="% url 'mailbox:inbox' %">
          <i class="fas fa-fw fa-table"></i>
          <span>Trash</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Tickets
      </div>

      <!-- Nav Item - My Tickets Menu -->
      <li {% if 'tickets/my_tickets' in request.path %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
        <a class="nav-link" href="{% url 'tickets:customer-my-tickets' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>My Tickets</span></a>
      </li>
      <li {% if 'tickets/submit' in request.path %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
        <a class="nav-link" href="{% url 'tickets:submit' %}">
          <i class="fas fa-fw fa-table"></i>
          <span>Submit a ticket</span></a>
      </li>
{% endblock sidebar_menu %}