OpenTicketing/openticketing/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls import url

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('', include('web_app.urls')),
    path('tickets/', include('tickets.urls')),
    path('admin/', admin.site.urls),
    url(r'^api/auth/login$', obtain_jwt_token, name='api-login'),
    path('', include('frontend.urls')),
]

urlpatterns += staticfiles_urlpatterns()

OpenTicketing/tickets/urls.py
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenTicketing, 
#    Copyright (C) 2019-2020 OpenTicketing (<https://github.com/loghmanb/OpenTicketing>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

from tickets.app_views.pages.dashboard import dashboard
from tickets.app_views.tickets.my_tickets import MyTickets
from tickets.app_views.tickets.ticket import TicketView


app_name = 'tickets'

urlpatterns = [
    path('', dashboard, name='home'),
    path('ticket/<int:id>', login_required(TicketView.as_view()), name='ticket'),

    path('dashboard/', dashboard, name='dashboard'),
    path('submitter/<int:id>', views.submitter, name='submitter'),

    path('my_tickets/', MyTickets.as_view(), name='customer-my-tickets'),
    path('submit/', views.submit, name='submit'),

    url('api/', include(('tickets.api.urls', 'tickets'), namespace="ticket-api")),
]

OpenTicketing/web_app/urls.py
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenTicketing, 
#    Copyright (C) 2019-2020 OpenTicketing (<https://github.com/loghmanb/OpenTicketing>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from django.conf.urls import url
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'web'

urlpatterns = [
    path('standard', views.home, name='home'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name='openticketing/logout.html'), name='logout'),
    path('user-profile/', views.user_profile, name='user-profile'),
    path('user-settings/', views.user_setting, name='user-settings'),
]

OpenTicketing/templates/openticketing/dashboard.html
{% extends "openticketing/layout.html" %}


{% block title %}
Dashboard - My tickets
{% endblock %}

{% block page_heading %}Dashboard{% endblock page_heading %}

{% block page_content %}
    {% if tickets %}
    <ul>
        {% for ticket in tickets %}
            {% if ticket.submitter %}
            <li><a href="{% url 'tickets:submitter' ticket.submitter.id %}">{{ticket.submitter}} [{{ ticket.submitter.id }}]</a>: <a href="{% url 'tickets:ticket' ticket.id %}">{{ticket.subject}} </a></li>
            {% else %}
            <li>Anonymous: <a href="{% url 'tickets:ticket' ticket.id %}">{{ticket.subject}} </a></li>
            {% endif %}
        {% endfor %}
    </ul>
    {% else %}
    <p>No ticket found!</p>
    {% endif %}


<div class="row">

            <!-- Area Chart -->
            <div class="col-xl-8 col-lg-7">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Submitted Tickets Overview</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <div class="chart-area"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                    <canvas id="submittedTicketChart" style="display: block; height: 320px; width: 782px;" width="977" height="400" class="chartjs-render-monitor"></canvas>
                  </div>
                </div>
              </div>
            </div>

            <!-- Pie Chart -->
            <div class="col-xl-4 col-lg-5">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Not Resolved Tickets</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink" style="position: absolute; transform: translate3d(-157px, 18px, 0px); top: 0px; left: 0px; will-change: transform;" x-placement="bottom-end">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <div class="chart-pie pt-4 pb-2"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                    <canvas id="ticketStatusPieChart" width="447" height="306" class="chartjs-render-monitor" style="display: block; height: 245px; width: 358px;"></canvas>
                  </div>
                </div>
              </div>
            </div>
          </div>



{% endblock %}


{% block jquery %}
<script type="text/javascript">
var endpoint = "{% url 'tickets:ticket-api:api-analytics-history' %}";
$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
      var ctx = document.getElementById('submittedTicketChart');
      var myChart = new Chart(ctx, data);
    },
    error: function(error){
      console.log(error);
    }
});

endpoint = "{% url 'tickets:ticket-api:api-analytics-status' %}";
$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
      data = {
        type: 'pie',
        data: {
          labels: ["<30 days", "30~60 days", ">60days"],
          datasets: [{
            label: "No. of tickets",
            backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f"],
            data: [2478,5267,734]
          }]
        }
      }
      var ctx = document.getElementById('ticketStatusPieChart');
      var myChart = new Chart(ctx, data);
    },
    error: function(error){
      console.log(error);
    }
});
</script>
{% endblock %}

OpenTicketing/templates/openticketing/home.html
{% extends 'openticketing/base.html' %}
{% block content %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" >
  <!-- Image Logo -->
  <a class="navbar-brand logo-image" href="{% url 'web:home' %}"><img src="{% static 'openticketing/img/logo.png' %}" alt="OpenTicketing"></a>

  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navb">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link page-scroll active" href="{% url 'web:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link page-scroll" href="#about">Documentation</a>
      </li>
      <li class="nav-item">
        <a class="nav-link page-scroll" href="#about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link page-scroll" href="#contact">Contact</a>
      </li>
    </ul>
    
    <div class="my-2 my-lg-0">
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Welcome {{ request.user }}!</a>
                <div class="dropdown-menu">
                  {% if request.user.is_superuser %}<a class="dropdown-item" href="{% url 'admin:index' %}">Admin page</a>{% endif %}
                  <a class="dropdown-item" href="{% url 'tickets:home' %}">Dashboard</a>
                  <a class="dropdown-item" href="{% url 'web:logout' %}">Logout</a>
                </div>
            </li>
            {% endif %}

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">English</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="#">English</a>
                  <a class="dropdown-item" href="#">Persian</a>
                </div>
            </li>

            {% if not request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link page-scroll" href="{% url 'tickets:home' %}">Login</a>
            </li>
            {% endif %}
            
        </ul>
    </div>
  </div>
</nav>

<header id="header" class="header">
  <div class="header-content" style="padding-top: 85px;">
    <div class="container-fluid">
      <div class="row">
        <ul>
        <li><a href="{% url 'tickets:dashboard' %}">Dashboard</a></li>
        </ul>
      </div>
    </div>
  </div>
</header>

<div class="container-fluid gedf-wrapper">
    <div class="row">
        <div class="col-md-3">
          {% if blog_posts %}
            {% for blog_post in blog_posts %}
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">{{ blog_post.name }}</h6>
                </div>
                <div class="card-body">
                  <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>
                      Wrote by {{ blog_post.create_user.get_full_name }} on {{ blog_post.create_date }}
                  </div>
                {{ blog_post.body }}
                </div>
            </div>
            {% endfor %}
          {% else %}
            <div class="card">
                <div class="card-body">
                No blog Post found!
                </div>
            </div>
          {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

OpenTicketing/templates/openticketing/layout.html
{% extends "openticketing/base.html" %}
{% block content %}
<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    {% include 'openticketing/partials/_sidebar_client.html' %}

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - Alerts -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>

            <!-- Nav Item - Messages -->
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div class="font-weight-bold">
                    <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                    <div class="small text-gray-500">Emily Fowler · 58m</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                    <div class="status-indicator"></div>
                  </div>
                  <div>
                    <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                    <div class="small text-gray-500">Jae Chun · 1d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                    <div class="status-indicator bg-warning"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                    <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                    <div class="small text-gray-500">Chicken the Dog · 2w</div>
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
              </div>
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user}}</span>
                <img class="img-profile rounded-circle" src="https://lh3.googleusercontent.com/-fWiQ2ZNd9d4/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rd4CGnSq3wjA_utFFF6KGDjUn9OoQ.CMID/s32-c/photo.jpg">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'web:user-profile' %}">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <a class="dropdown-item" href="{% url 'web:user-settings' %}">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Settings
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                  Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'web:logout' %}">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800">{% block page_heading %}{% endblock page_heading %}</h1>
          {% block page_content %}
          {% endblock page_content %}
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      {% include 'openticketing/partials/_footer.html' %}

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

{% endblock %}

OpenTicketing/templates/openticketing/login.html
{% extends 'openticketing/base.html' %}
{% block title %}
Login - OpenTicketing
{% endblock %}
{% if request.user.is_authenticated %}
        <meta http-equiv="REFRESH" content="0;url={% url 'tickets:home' %}">
{% else %}
    {% block content %}
    {% load static %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-6 col-lg-10 col-md-6 row">
                <div class="card o-hidden border-0 shadow-lg my-2">
                    <div class="card-body p-0">
                        <div class="col-12">
                            <img class="img-fluid" src="{% static 'openticketing/img/logo.png' %}" />
                        </div>
                        <div class="col-12">
                            <div class="p-5">
                                <form role="form" method='post' action='./' class="user">
                                    {% csrf_token %}
                                    {% if form.errors %}
                                        <div class="alert alert-danger"> "Your username and password didn't match. Please try again."</div>
                                    {% endif %}                                        
                                    <div class="form-group">
                                        <input class="form-control form-control-user" placeholder="Enter username" name="username" type="text" autofocus>
                                    </div>
                                    <div class="form-group">
                                        <input class="form-control form-control-user" placeholder="Password" name="password" type="password" value="">
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input name="remember" type="checkbox" value="Remember Me"> 'Remember Me'
                                        </label>
                                    </div>
                                    <input class="btn btn-primary btn-user btn-block" type='submit' value=' "Login" ' />
                                    <input type="hidden" name="next" value="{% if next %}{{ next }}{% else %}../{% endif %}" />
                                    <a href="index.html" class="btn btn-google btn-user btn-block">
                                        <i class="fab fa-google fa-fw"></i> Login with Google
                                    </a>
                                    <hr />
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
{% endif %}

OpenTicketing/templates/openticketing/submit_ticket.html
{% extends "openticketing/layout.html" %}
{% block title %}
Submit a ticket
{% endblock %}

{% block page_heading %}Submit a ticket{% endblock page_heading %}

{% load crispy_forms_tags %}

{% block page_content %}
<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="row">
                <div class="col-lg-6">
                    {% if is_ticket_submitted %}
                        <div>
                            {{ message }}
                            <ul>
                                <li>for track your ticket you can <a href="{% url 'tickets:ticket' ticket_id %}">clicke here</a></li>
                                <li>for submit new ticket you can <a href="{% url 'tickets:submit'%}">clicke here</a></li>
                            </ul>
                        </div>
                    {% else %}
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {{ form | crispy }}
                        <div class="form-group">
                            <label>Attachments</label>
                            <input type="file" name="attachments">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock page_content %}

OpenTicketing/templates/openticketing/temporary.html
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom bg-dark fixed-top">

        <!-- Image Logo -->
        <a class="navbar-brand logo-image" href="{% url 'tickets:home' %}"><img src="{% static 'openticketing/img/logo.png' %}" alt="OpenTicketing"></a>
        
        <!-- Mobile Menu Toggle Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-awesome fas fa-bars"></span>
            <span class="navbar-toggler-awesome fas fa-times"></span>
        </button>
        <!-- end of mobile menu toggle button -->

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link page-scroll active" href="{% url 'tickets:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>

                <li class="nav-item">
                    <a class="nav-link page-scroll" href="#about">Documentation</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link page-scroll" href="#about">About</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link page-scroll" href="#contact">Contact</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link page-scroll" href="#language">Select Language</a>
                </li>

                <li>
                {% if request.user.is_authenticated %}
                    <a  class="nav-link page-scroll" href="#">{{ request.user }}</a>
                </li>
                <li>
                    <a  class="nav-link page-scroll" href="{% url 'web:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-link page-scroll" href="{% url 'tickets:home' %}">Login</a>
                {% endif %}
                </li>
            </ul>
            <span class="nav-item social-icons">
                <span class="fa-stack">
                    <a href="http://github.com/loghmanb">
                        <i class="fas fa-circle fa-stack-2x facebook"></i>
                        <i class="fab fa-git-f fa-stack-1x"></i>
                    </a>
                </span>
                <span class="fa-stack">
                    <a href="#your-link">
                        <i class="fas fa-circle fa-stack-2x facebook"></i>
                        <i class="fab fa-facebook-f fa-stack-1x"></i>
                    </a>
                </span>
                <span class="fa-stack">
                    <a href="#your-link">
                        <i class="fas fa-circle fa-stack-2x twitter"></i>
                        <i class="fab fa-twitter fa-stack-1x"></i>
                    </a>
                </span>
            </span>
        </div>
    </nav>