OpenTicketing/openticketing/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf.urls import url

from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('', include('web_app.urls')),
    path('tickets/', include('tickets.urls')),
    path('admin/', admin.site.urls),
    url(r'^api/auth/login$', obtain_jwt_token, name='api-login'),
    path('', include('frontend.urls')),
]

urlpatterns += staticfiles_urlpatterns()

OpenTicketing/tickets/api/urls.py
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenTicketing, 
#    Copyright (C) 2019-2020 OpenTicketing (<https://github.com/loghmanb/OpenTicketing>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from django.conf.urls import url
from django.urls import path

from .analytics.chart import TicketHistoryData
from .ticket import TicketRUDView, TicketListView

urlpatterns = [
    path('api/analytics/ticket-history', TicketHistoryData.as_view(), name='api-analytics-history'),
    path('api/analytics/ticket-status', TicketHistoryData.as_view(), name='api-analytics-status'),

    # Example: http://127.0.0.1:8000/tickets/api/1/
    url(r'^(?P<id>\d+)/$', TicketRUDView.as_view(), name='ticket-rud'),
    url(r'^$', TicketListView.as_view(), name='listcreate'),
]

OpenTicketing/tickets/urls.py
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenTicketing, 
#    Copyright (C) 2019-2020 OpenTicketing (<https://github.com/loghmanb/OpenTicketing>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

from tickets.app_views.pages.dashboard import dashboard
from tickets.app_views.tickets.my_tickets import MyTickets
from tickets.app_views.tickets.ticket import TicketView


app_name = 'tickets'

urlpatterns = [
    path('', dashboard, name='home'),
    path('ticket/<int:id>', login_required(TicketView.as_view()), name='ticket'),

    path('dashboard/', dashboard, name='dashboard'),
    path('submitter/<int:id>', views.submitter, name='submitter'),

    path('my_tickets/', MyTickets.as_view(), name='customer-my-tickets'),
    path('submit/', views.submit, name='submit'),

    url('api/', include(('tickets.api.urls', 'tickets'), namespace="ticket-api")),
]

OpenTicketing/tickets/models.py
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenTicketing, 
#    Copyright (C) 2019-2020 OpenTicketing (<https://github.com/loghmanb/OpenTicketing>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from datetime import datetime

from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from rest_framework.reverse import reverse as api_reverse

from utils.models import AbstractModel
from web_app.models import Department, Organization, Category


class Ticket(AbstractModel):
    class Meta:
        db_table = 'ot_ticket'

    PRIORITIES = [
        (1, _('High')),
        (2, _('Normal')),
        (3, _('Low')),
    ]
    
    STATUS = [
        (1, _('Draft')),
        (2, _('Open')),
        (3, _('Closed')),
        (4, _('Pending')),
    ]

    subject = models.CharField(max_length=200, verbose_name=_('Subject'))
    description = models.TextField(verbose_name=_('Description'))
    department = models.ForeignKey(Department, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('Department'))
    category = models.ForeignKey(Category, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('Help Topics'))
    submitter = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='submitter_uid',
        blank=True,
        null=True,
        verbose_name=_('Submitter'),
    )
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('Organization'))
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='assigned_uid',
        blank=True,
        null=True,
        verbose_name=_('Assigned to'),
    )
    priority = models.IntegerField(verbose_name=_('Priority'), choices=PRIORITIES, default=2)
    status = models.IntegerField(verbose_name=_('Status'), choices=STATUS, default=1)
    starred = models.BooleanField(verbose_name=_('Starred'), default=False)
    dependencies = models.ManyToManyField("self", blank=True)

    def get_comments(self):
        if self.comments.count():
            return self.comments.order_by('-create_date')

    @property
    def owners(self):
        return [self.create_user, self.assigned_to, self.submitter]

    def get_api_url(self, request=None):
        return api_reverse("tickets:ticket-api:ticket-rud", kwargs={'id':self.pk}, request=request)

    def __str__(self):
        return f"{self.subject} [{self.submitter}]"


class TicketAttachments(AbstractModel):
    class Meta:
        db_table = 'ot_ticket_attachments'
    
    name = models.CharField(max_length=100, verbose_name=_('Name'))
    ticket = models.ForeignKey(
        Ticket,
        on_delete=models.CASCADE,
        related_name='attachments',
        blank=True,
        null=True,
        verbose_name=_('Ticket')
    )
    doc_file = models.FileField(upload_to='documents/%Y/%m/%d')

    def __str__(self):
        return self.name

class Comment(AbstractModel):
    class Meta:
        db_table = 'ot_comment'

    ticket = models.ForeignKey(
        Ticket,
        on_delete=models.CASCADE,
        related_name='comments',
        blank=True,
        null=True,
        verbose_name=_('Ticket')
    )
    name = models.CharField(max_length=128, verbose_name=_('Name'))
    note = models.TextField(verbose_name=_('Note'))

OpenTicketing/tickets/forms.py
from django import forms

from .models import Ticket

class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['department', 'category', 'subject', 'description', 'priority']

    def __init__(self, *args, **kwargs):
        super(TicketForm, self).__init__(*args, **kwargs)
        self.fields['subject'].widget.attrs.update({'placeholder' : 'Please enter a brief summary here'})
        self.fields['subject'].label = ''
        self.fields['description'].widget.attrs.update({'placeholder' : 'Please describe the ticket in more details'})
        self.fields['description'].label = ''
        

OpenTicketing/tickets/views.py
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenTicketing, 
#    Copyright (C) 2019-2020 OpenTicketing (<https://github.com/loghmanb/OpenTicketing>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################

from django.contrib.auth import models
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from .models import Ticket
from .forms import TicketForm


@login_required
def user_settings(request):
    return HttpResponse('User settings page goes here!')

@login_required
def user_activity_log(request):
    return HttpResponse('User activities log goes here!')


@login_required
def submit(request):
    is_ticket_submitted = False
    ticket_id = None
    message = ''
    if request.method=='POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            ticket = form.save()
            is_ticket_submitted = True
            ticket_id = ticket.id
            message = f"'{request.POST['subject']}' is submitted succesfuly!"
    else:
        form = TicketForm()
    return render(request, 'openticketing/submit_ticket.html', 
                  context=dict(form=form, is_ticket_submitted=is_ticket_submitted, ticket_id=ticket_id, message=message))


def submitter(request, id):
    submitter = get_object_or_404(models.User, pk=id)
    return HttpResponse(f'submitter: {id} - {submitter}')

OpenTicketing/templates/openticketing/tickets/my_tickets.html
{% extends 'openticketing/layout.html' %}
{% block page_content %}

<ul class="nav nav-tabs" style="margin-bottom: 15px;">
    <li class="nav-item">
        <a class="nav-link active" href="#openTickets" data-toggle="tab">Open</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#closedTickets" data-toggle="tab">Closed</a>
    </li>
</ul>
<div id="myTabContent" class="tab-content">
    <div class="tab-pane active in" id="openTickets">
        {% if open_tickets %}
            <table id="example" class="display" style="width:100%">
                <thead>
                    <tr>
                        <th>Help Topic</th>
                        <th>Subject</th>
                        <th>Submitter</th>
                        <th>Asigned to</th>
                        <th>Priority</th>
                        <th>Department</th>
                        <th>Create date</th>
                    </tr>
                </thead>
                <tbody>
                {% for ticket in open_tickets %}
                    <tr>
                        <td>{{ ticket.category }}</td>
                        <td><a href="{% url 'tickets:ticket' ticket.id %}">{{ ticket.subject }}</td>
                        <td>{{ ticket.submitter }}</td>
                        <td>{{ ticket.assigned_to }}</td>
                        <td>{{ ticket.priority }}</td>
                        <td>{{ ticket.department }}</td>
                        <td>{{ ticket.create_date }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            {% if open_tickets.has_other_pages %}
            <ul class="pagination">
                {% if open_tickets.has_pervious %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">&laquo; first</a>
                    </li>
                    <a href="?page={{ openTickets.previous_page_number }}">previous</a>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&laquo;</a>
                    </li>
                {% endif %}
                {% for i in open_tickets.paginator.page_range %}
                    {% if open_tickets.number == i %}
                    <li class="page-item active">
                        <a class="page-link">{{ i }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                    </li>
                    {% endif %}
                {% endfor %}

                {% if open_tickets.has_next %}
                    <li class="page-item">
                        <a href="?page={{ open_tickets.paginator.num_pages }}" class="page-link">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-link disabled">
                        <a class="page-link">&raquo;</a>
                    </li>
                {% endif %}
            </ul>
            {% endif %}
        {% else %}
            <div>
                <p>Congratulations! No open tickets found!</p>
            </div>
        {% endif %}
    </div>
    <div class="tab-pane fade " id="closedTickets">
        <p>History of closed ticket goes here!</p>
    </div>
</div>
<div>
    Do you have any problem?! So, <a href="{% url 'tickets:submit' %}">submit a ticket</a>
</div>

{% endblock page_content %}

OpenTicketing/templates/openticketing/tickets/ticket.html
{% extends 'openticketing/layout.html' %} {% block page_content %}

<style>
body {
            background-color: #eeeeee;
        }

        .h7 {
            font-size: 0.8rem;
        }

        .gedf-wrapper {
            margin-top: 0.97rem;
        }

        @media (min-width: 992px) {
            .gedf-main {
                padding-left: 4rem;
                padding-right: 4rem;
            }
            .gedf-card {
                margin-bottom: 2.77rem;
            }
        }

        /**Reset Bootstrap*/
        .dropdown-toggle::after {
            content: none;
            display: none;
        }
</style>

<nav class="navbar navbar-light bg-white">
    <i class="fa fa-star"><a href="#" class="navbar-brand">{{ ticket.subject }}</a></i>
</nav>

<div class="container-fluid gedf-wrapper">
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <div class="h5">{{ ticket.organization }}</div>
                    <div class="h7 text-muted">Department: {{ ticket.department }}</div>
                    <div class="h7">Submitter: {{ ticket.submitter.get_full_name }}</div>
                    <div class="h7">Assigned to: {{ ticket.assigned_to.get_full_name }}</div>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-md-6 text-center">
                                <div class="h6 text-muted">Priority</div>
                                <div class="h5">{{ ticket.get_priority_display }}</div>
                            </div>
                            <div class="col-md-6 text-center">
                                <div class="h6 text-muted">Status</div>
                                <div class="h5">{{ ticket.get_status_display }}</div>
                            </div>
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="h6">Dependencies</div>
                        <div class="h7">
                            {% if not ticket.dependencies.count %}No Dependency{% endif %}
                            {% for dependency in ticket.dependencies.all %}
                                <span class="label label-primary">{{ dependency.name }}</span>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="h6">Attachments</div>
                        <div class="h7">
                            {% if not ticket.attachments.count %}No attachments{% endif %}
                            {% for attachemnt in ticket.attachments.all %}
                                <span class="label label-primary">{{ attachemnt.name }}</span>
                            {% endfor %}
                        </div>
                    </li>
                    <li class="list-group-item">
                        <div class="h6">Description</div>
                        <div class="h7 text-muted">{{ ticket.description }}</div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-md-6 gedf-main">
            <div class="card gedf-card">
                <div class="card-header">
                    <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">Make
                                a publication</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="images-tab" data-toggle="tab" role="tab" aria-controls="images" aria-selected="false" href="#images">Images</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                            <div class="form-group">
                                <label class="sr-only" for="message">post</label>
                                <textarea class="form-control" id="message" rows="3" placeholder="What are you thinking?"></textarea>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
                            <div class="form-group">
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="customFile">
                                    <label class="custom-file-label" for="customFile">Upload image</label>
                                </div>
                            </div>
                            <div class="py-4"></div>
                        </div>
                    </div>
                    <div class="btn-toolbar justify-content-between">
                        <div class="btn-group">
                            <button type="submit" class="btn btn-primary">share</button>
                        </div>
                        <div class="btn-group">
                            <button id="btnGroupDrop1" type="button" class="btn btn-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-globe"></i>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="btnGroupDrop1">
                                <a class="dropdown-item" href="#"><i class="fa fa-globe"></i> Public</a>
                                <a class="dropdown-item" href="#"><i class="fa fa-users"></i> Friends</a>
                                <a class="dropdown-item" href="#"><i class="fa fa-user"></i> Just me</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!--- \\\\\\\Post-->
            {% for comment in ticket.get_comments %}
            <div class="card gedf-card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="mr-2">
                                <img class="rounded-circle" width="45" src="https://picsum.photos/50/50" alt="">
                            </div>
                            <div class="ml-2">
                                <div class="h5 m-0">{{ comment.create_user.get_full_name }}</div>
                                <div class="h7 text-muted">{{ comment.create_date }}</div>
                            </div>
                        </div>
                    <div>
                    <div class="dropdown">
                        <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-ellipsis-h"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                            <div class="h6 dropdown-header">Configuration</div>
                                <a class="dropdown-item" href="#">Save</a>
                                <a class="dropdown-item" href="#">Hide</a>
                                <a class="dropdown-item" href="#">Report</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i>
                    {% if comment.write_date %}
                    Edited by {{ comment.write_user.get_full_name }} on {{ comment.write_date }}
                    {% endif %}
                </div>
                <a class="card-link" href="#">
                    <h5 class="card-title">{{ comment.name }}</h5>
                </a>
                <p class="card-text">{{ comment.note }}</p>
            </div>

            <div class="card-footer">
                <a href="#" class="card-link"><i class="fa fa-gittip"></i> Like</a>
                <a href="#" class="card-link"><i class="fa fa-comment"></i> Comment</a>
                <a href="#" class="card-link"><i class="fa fa-mail-forward"></i> Share</a>
            </div>
        </div>
        {% endfor %}
                <!-- Post /////-->
            </div>
            <div class="col-md-3">
                <div class="card gedf-card">
                    <div class="card-body">
                        <h5 class="card-title">Note 1</h5>
                        <h6 class="card-subtitle mb-2 text-muted">Note 1 subtitle</h6>
                        <p class="card-text">Some quick example text to build on the note title and make up the bulk of the
                            ticket note's content.</p>
                        <a href="#" class="card-link">Note link</a>
                        <a href="#" class="card-link">Another link</a>
                    </div>
                </div>
                <div class="card gedf-card">
                        <div class="card-body">
                            <h5 class="card-title">Note 2 title</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Note 2 subtitle</h6>
                            <p class="card-text">Some quick example text to build on the note title and make up the bulk of the
                                note's content.</p>
                            <a href="#" class="card-link">Note link</a>
                            <a href="#" class="card-link">Another link</a>
                        </div>
                    </div>
            </div>
        </div>
    </div>



{% endblock %}